targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator: # this for @RoutePage
        options:
        generate_for:
          - lib/screens/*.dart
          - lib/**/**_screen.dart
          - lib/**/**_page.dart
      auto_route_generator:auto_router_generator: # this for @AutoRouterConfig
        options:
        generate_for:
          - lib/managers/**/app_router.dart
